# Game Theory With Python

### Welcome to the course. 
### Glad to have you onboard in this journey to explore two Game Theory packages in Python

#### Nashpy 

#### 7 Tasks
#### 1. Create games with Nashpy
#### 2. Mixed strategies and Utilities
#### 3. Nash Equilibrium
#### 4. Games with multiple Nash Equilibria
#### 5. Zero Sum Game


## Two Player Games with Nashpy

## 1. Create 2 player games - Using Nashpy

### Consider the following Prisoner's Dilemma matrix

![picture](https://drive.google.com/uc?id=1fw7j7O8XLGQR3Rt_c9UK_PE6KgLsFeEw)


In [1]:
# Import packages
!pip install nashpy
#!pip install axelrod


In [10]:
import nashpy as nash
import numpy as np

In [11]:
# Create the payoff matrix

P1 =  np.array([[8,1],[15,3]])# P1 is the row player
P2 =  np.array([[8,15],[1,3]])# P2 is the column player
pd = nash.Game(P1, P2)
pd


Bi matrix game with payoff matrices:

Row player:
[[ 8  1]
 [15  3]]

Column player:
[[ 8 15]
 [ 1  3]]

### Exercise: Create a two player game, where,

#### I. Name players as A and B
#### II. Name the game as 'gm' and 
#### III. Use the follwing matrix

![picture](https://drive.google.com/uc?id=1eHhyXZVZWQ3oPto4qcbL1EefxUsWq4bp)


In [23]:
A = np.array([[5, 17],[14,12]])
B = np.array([[15, 16],[2, 8]])
gm = nash.Game(A,B)
gm

Bi matrix game with payoff matrices:

Row player:
[[ 5 17]
 [14 12]]

Column player:
[[15 16]
 [ 2  8]]

## 2. Mixed Strategy and Utilities

### Pure Strategy: 

A complete definition of how a player will play a game, it yields optimum payoff to the player. 

### Mixed Strategy: 

Assigns a probability to each pure strategy. This allows for a player to randomly select a pure strategy. 

### Calculating Utilities:

![picture](https://drive.google.com/uc?id=1eIMuJo8w5EgJC5mLaxT9kzH8-rdQwm3_)

#### Consider the following Mixed Strategy

σr=(.2,.8) and σc=(.6,.4)


In [14]:
# Calculate Utilities

sigma_r = np.array([0.2, 0.8])
sigma_c = np.array([0.6, 0.4])
pd = nash.Game(P1, P2)
pd[sigma_r, sigma_c]

array([9.2, 3.6])

In [8]:
pd

Bi matrix game with payoff matrices:

Row player:
[[ 8  1]
 [15  3]]

Column player:
[[ 8 15]
 [ 1  3]]

### Validate the computation

In [15]:
#ur(σr,σc)
ur=0.2*0.6*8+0.2*0.4*1+0.8*0.6*15+0.8*0.4*3
ur

9.2

In [16]:
#uc(σr,σc)
uc=0.2*0.6*8+0.2*0.4*15+0.8*0.6*1+0.8*0.4*3
uc

3.6000000000000005

### Exercise: Calculate the utilities of the game 'gm' created in the previous exercise, using 
#### σr=(.3,.7) and σc=(.5,.5)

In [24]:
sigma_r = np.array([.3, .7])
sigma_c = np.array([.5, .5])
gm = nash.Game(A,B)
gm[sigma_r, sigma_c]

array([12.4 ,  8.15])

## 3. The Nash Equilibrium

Strict and unique Nash Equilibrium

![picture](https://drive.google.com/uc?id=1_B9Wk5Sb1jwK1AADXR1xj9n0tmALNykM)

In [18]:
# Find the Nash Equilibrium with Support Enumeration

equilibria = pd.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([0., 1.]))


#### Both solutions match

### Exercise: Find out the Nash Equilibrium for gm

In [26]:
equilibria = gm.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([0., 1.]))


In [27]:
gm

Bi matrix game with payoff matrices:

Row player:
[[ 5 17]
 [14 12]]

Column player:
[[15 16]
 [ 2  8]]

## 4. Games with Multiple Nash Equilibria

### Hawk - Dove Game

![picture](https://drive.google.com/uc?id=1b8kKho3qu1s5b7Qriq6NYWqJxd5uKI6x)

In [29]:
P3 =  np.array([[3, 1], [4, 0]])# P3 is the row player
P4 =  np.array([[3, 4], [1, 0]])# P4 is the column player 
hd = nash.Game(P3, P4)
hd

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [4 0]]

Column player:
[[3 4]
 [1 0]]

#### Nash Equilibria

![picture](https://drive.google.com/uc?id=1JJxdwZ3y6U_hxMH-0l4i6LpuuTVhF5w0)


In [30]:
equilibria = hd.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0.5, 0.5]), array([0.5, 0.5]))


Sol. (D,H)

P3 : D = 1, H = 0

P4 : D = 0, H = 1

Sol. (H,D)

P3 : D = 0, H = 1

P4 : D = 1, H = 0

Sol. (D,D) or (H,H)

P3 : D = 0.5, H = 0.5

P4 : D = 0.5, H = 0.5


### Exercise: Find out the number of NE for the following matrix
#### Players: M and N
#### Name of game mn


![picture](https://drive.google.com/uc?id=1mAeVXw3qHTyzEx4kgMsOlyrP6rJvpKlN)

In [33]:
M = np.array([[1, 1, 3, 2], [2, 3, 4, 3], [5, 1, 1, 4]])
N = np.array([[3, 2, 2, 4],[1, 4, 2, 0],[3, 3, 2, 3]])
mn = nash.Game(M, N)
mn

Bi matrix game with payoff matrices:

Row player:
[[1 1 3 2]
 [2 3 4 3]
 [5 1 1 4]]

Column player:
[[3 2 2 4]
 [1 4 2 0]
 [3 3 2 3]]

In [34]:
equilibria = mn.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1., 0.]), array([0., 1., 0., 0.]))
(array([0., 0., 1.]), array([1., 0., 0., 0.]))
(array([0., 0., 1.]), array([0., 0., 0., 1.]))


![picture](https://drive.google.com/uc?id=11UeEgrEh4VYWYAMwyvwLVGZlHT7On2Eo)

## 5. Zero Sum Game

Matching the pennies game

![picture](https://drive.google.com/uc?id=1DJhLFiRbUah8Cvku03oGP5C2eFuDPxBQ)

In [35]:
P5 = np.array([[1, -1],[-1, 1]])
P6 = np.array([[-1, 1],[1, -1]])
mp = nash.Game(P5, P6)
mp

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [36]:
equilibria = mp.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0.5, 0.5]), array([0.5, 0.5]))


### Exercise: Find out the solution for the following zero sum game 'zs'
#### Use payoff matrix - np.array([[5, -6.5], [-2.5, 7]]) 
#### For players Z1 and Z2

In [38]:
Z1 = np.array([[5, -6.5], [-2.5, 7]])
Z2 = np.array([[5, -6.5], [-2.5, 7]])

In [39]:
Z12 = nash.Game(Z1, Z2)
for eq in Z12.support_enumeration():
    print(eq)

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([0.45238095, 0.54761905]), array([0.64285714, 0.35714286]))


## Two Player-Repeated Games with Axelrod

## 6. Create repeated game

In [40]:
#!pip install -U pyYAML     # Troubleshoot: Execute this line if Axelrod does not run and AttributeError: module 'yaml' has no attribute 'FullLoader' occurs

# Import package

import axelrod as axl

In [42]:
# Create matches

players = (axl.Cooperator(), axl.Alternator())                  # using players of Cooperator and Alternator strategy
match1 =  axl.Match(players, turns=5)                           # play for 5 turns
match1.play()

[(C, C), (C, D), (C, C), (C, D), (C, C)]

In [43]:
axl.all_strategies

[axelrod.strategies.memoryone.ALLCorALLD,
 axelrod.strategies.memorytwo.AON2,
 axelrod.strategies.apavlov.APavlov2006,
 axelrod.strategies.apavlov.APavlov2011,
 axelrod.strategies.adaptive.Adaptive,
 axelrod.strategies.titfortat.AdaptiveTitForTat,
 axelrod.strategies.adaptor.AdaptorBrief,
 axelrod.strategies.adaptor.AdaptorLong,
 axelrod.strategies.grudger.Aggravater,
 axelrod.strategies.titfortat.Alexei,
 axelrod.strategies.alternator.Alternator,
 axelrod.strategies.hunter.AlternatorHunter,
 axelrod.strategies.cycler.AntiCycler,
 axelrod.strategies.titfortat.AntiTitForTat,
 axelrod.strategies.appeaser.Appeaser,
 axelrod.strategies.qlearner.ArrogantQLearner,
 axelrod.strategies.averagecopier.AverageCopier,
 axelrod.strategies.backstabber.BackStabber,
 axelrod.strategies.better_and_better.BetterAndBetter,
 axelrod.strategies.titfortat.Bully,
 axelrod.strategies.bush_mosteller.BushMosteller,
 axelrod.strategies.calculator.Calculator,
 axelrod.strategies.qlearner.CautiousQLearner,
 axelro

### Exercise: Create a repeated game with 2 players having:
#### I. TitForTat and Random Strategy 
#### II. Name it as match2
#### III. Run it for 15 turns

In [64]:
players = (axl.TitForTat(), axl.Random())
match2 = axl.Match(players, turns=15)
match2.play()

[(C, D),
 (D, C),
 (C, C),
 (C, C),
 (C, C),
 (C, C),
 (C, D),
 (D, D),
 (D, D),
 (D, C),
 (C, D),
 (D, D),
 (D, D),
 (D, C),
 (C, C)]

## 7. Analyze Match

In [48]:
# Payoffs

match1.game        #Analyze the match

#These payoffs are commonly referred to as:

#R: the Reward payoff (default value in the library: 3) C-C
#P: the Punishment payoff (default value in the library: 1) D-D
#S: the Loss payoff (default value in the library: 0) C-D
#T: the Temptation payoff (default value in the library: 5) D-C

Axelrod game: (R,P,S,T) = (3, 1, 0, 5)

In [49]:
# Scores of a match

match1.scores()     #Retrieve match scores

[(3, 3), (0, 5), (3, 3), (0, 5), (3, 3)]

In [50]:
# The result of the match can also be viewed as sparklines where cooperation is shown as a solid block and defection as a space. 

print(match1.sparklines())  # Get output using sparklines

█████
█ █ █


### Exercise: Analyze match2. 
#### Find the score and create the sparklines

In [65]:
match2.game

Axelrod game: (R,P,S,T) = (3, 1, 0, 5)

In [66]:
match2.scores()


[(0, 5),
 (5, 0),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (0, 5),
 (1, 1),
 (1, 1),
 (5, 0),
 (0, 5),
 (1, 1),
 (1, 1),
 (5, 0),
 (3, 3)]

In [67]:
print(match2.sparklines())

█ █████   █   █
 █████   █   ██


#### References:

Package Documentations

https://nashpy.readthedocs.io/en/stable/index.html#

https://axelrod.readthedocs.io/en/stable/#